### ISSUE TITLE
Crashing on Win 11

### ISSUE THREAD

**Issue by kevev** [featherbear/NDI-Telestrator#16]
Would it be possible to get a fix for Win 11? The app seems to crash after some time regularly. Thank You!

**Comment by kevev** [comment]
Info on the crash:

Faulting application name: NDI.Telestrator.v1.0.1.exe, version: 1.0.0.1, time stamp: 0xe7ffddb3
Faulting module name: KERNELBASE.dll, version: 10.0.22621.2792, time stamp: 0x3091b6fb
Exception code: 0xe0434352
Fault offset: 0x000000000006567c
Faulting process id: 0x0x41B0
Faulting application start time: 0x0x1DA46A3D4580425
Faulting application path: C:\NDI.Telestrator.v1.0.1.exe
Faulting module path: C:\Windows\System32\KERNELBASE.dll
Report Id: 53ed6b8f-11ef-46d3-8e9d-ea3f54cd60cb
Faulting package full name:
Faulting package-relative application ID:

**Comment by kevev** [comment]
More info on the crash:

Application: NDI.Telestrator.v1.0.1.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.ArgumentOutOfRangeException
   at System.ThrowHelper.ThrowArgumentOutOfRangeException(System.ExceptionArgument, System.ExceptionResource)
   at System.Collections.Generic.List`1[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].get_Item(Int32)
   at NDI_Telestrator.InkLayer.OnMouseLeftButtonUp(System.Windows.Input.MouseButtonEventArgs)
   at System.Windows.RoutedEventArgs.InvokeHandler(System.Delegate, System.Object)
   at System.Windows.RoutedEventHandlerInfo.InvokeHandler(System.Object, System.Windows.RoutedEventArgs)
   at System.Windows.EventRoute.InvokeHandlersImpl(System.Object, System.Windows.RoutedEventArgs, Boolean)
   at System.Windows.UIElement.ReRaiseEventAs(System.Windows.DependencyObject, System.Windows.RoutedEventArgs, System.Windows.RoutedEvent)
   at System.Windows.UIElement.OnMouseUpThunk(System.Object, System.Windows.Input.MouseButtonEventArgs)
   at System.Windows.RoutedEventArgs.InvokeHandler(System.Delegate, System.Object)
   at System.Windows.RoutedEventHandlerInfo.InvokeHandler(System.Object, System.Windows.RoutedEventArgs)
   at System.Windows.EventRoute.InvokeHandlersImpl(System.Object, System.Windows.RoutedEventArgs, Boolean)
   at System.Windows.UIElement.RaiseEventImpl(System.Windows.DependencyObject, System.Windows.RoutedEventArgs)
   at System.Windows.UIElement.RaiseTrustedEvent(System.Windows.RoutedEventArgs)
   at System.Windows.Input.InputManager.ProcessStagingArea()
   at System.Windows.Input.InputManager.ProcessInput(System.Windows.Input.InputEventArgs)
   at System.Windows.Input.InputProviderSite.ReportInput(System.Windows.Input.InputReport)
   at System.Windows.Interop.HwndMouseInputProvider.ReportInput(IntPtr, System.Windows.Input.InputMode, Int32, System.Windows.Input.RawMouseActions, Int32, Int32, Int32)
   at System.Windows.Interop.HwndMouseInputProvider.FilterMessage(IntPtr, MS.Internal.Interop.WindowMessage, IntPtr, IntPtr, Boolean ByRef)
   at System.Windows.Interop.HwndSource.InputFilterMessage(IntPtr, Int32, IntPtr, IntPtr, Boolean ByRef)
   at MS.Win32.HwndWrapper.WndProc(IntPtr, Int32, IntPtr, IntPtr, Boolean ByRef)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(System.Object)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(System.Delegate, System.Object, Int32)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(System.Object, System.Delegate, System.Object, Int32, System.Delegate)
   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(System.Windows.Threading.DispatcherPriority, System.TimeSpan, System.Delegate, System.Object, Int32)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr, Int32, IntPtr, IntPtr)
   at MS.Win32.UnsafeNativeMethods.DispatchMessage(System.Windows.Interop.MSG ByRef)
   at System.Windows.Threading.Dispatcher.PushFrameImpl(System.Windows.Threading.DispatcherFrame)
   at System.Windows.Application.RunDispatcher(System.Object)
   at System.Windows.Application.RunInternal(System.Windows.Window)
   at NDI_Telestrator.App.Main()

**Comment by kevev** [comment]
This seems to have been caused by Chrome Remote Desktop screen sharing. When screen sharing was disconnected, this app doesn't seem to crash anymore.

**Comment by featherbear** [comment]
Interesting to see https://github.com/featherbear/NDI-Telestrator/blob/master/InkLayer.cs#L251 breaking

I just tried to CRDP into my machine running the app - didn't crash for me...
<img width="643" alt="image" src="https://github.com/featherbear/NDI-Telestrator/assets/1159091/e1f54c90-0847-4d27-9a11-62fe9898475e">


What's your setup like?

**Comment by kevev** [comment]
Windows 11, Intel CPU, NVidia GPU. Using mouse or touch screen to draw.
